### ISSUE TITLE
MPD error: Connection refused

### ISSUE THREAD

**Issue by axel11** [MusicGenerator/mumble-ruby-pluginbot#232]
just tried to install the bot but it isnt working. i am running ubuntu 17.04

i try testing with the command `mpc -p 7701 status`

and it outputs the title

i also changed the host.allow file as well

I am also getting this on repeat in my log file.
`/home/botmaster/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require': /home/botmaster/src/mumble-ruby-pluginbot/plugins/mpd.rb:195: invalid multibyte char (US-ASCII) (SyntaxError)
/home/botmaster/src/mumble-ruby-pluginbot/plugins/mpd.rb:195: invalid multibyte char (US-ASCII)
/home/botmaster/src/mumble-ruby-pluginbot/plugins/mpd.rb:195: syntax error, unexpected $end, expecting keyword_end
...control:string")}shuffle</b> â€“ #{I18n.t("plugin_mpd.help.s...
...                               ^
	from /home/botmaster/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/botmaster/src/mumble-ruby-pluginbot/core/pluginbot.rb:4:in `block in <main>'
	from /home/botmaster/src/mumble-ruby-pluginbot/core/pluginbot.rb:4:in `each'
	from /home/botmaster/src/mumble-ruby-pluginbot/core/pluginbot.rb:4:in `<main>'`

**Comment by dafoxia** [comment]
I've removed the multibyte char and replaced it with a standard ASCII char in line 195.
Please pull again, this error should be fixed now.
I suggest you to use a more recent version of ruby. 
You don't mess up your system ruby if you do step by step in the official manual. (http://mumble-ruby-pluginbot.readthedocs.io/en/master/installation_howto.html#install-and-set-up-ruby-and-all-needed-libraries)
